### ISSUE TITLE
Incorrect dashboard in certain conditions

### ISSUE THREAD

**Issue by KSneijders** [SamJakob/github-homepage#1]
First of all, thanks for the plugin, it's working great ❤️! 

I noticed when going to the dashboard using the button (see image) the page will not show the old dashboard. Not sure if this is detectable in any way, but thought I'd let you know 🙂 

![image](https://github.com/SamJakob/github-homepage/assets/32707500/7e13a396-0f1d-4e1a-b158-7a0c8443b4bc)

I also noticed that when visiting `https://github.com/dashboard` the new dashboard is still showing.  
_Which is where you get redirected after clicking this link:_
![image](https://github.com/SamJakob/github-homepage/assets/32707500/b8a7d3e1-5598-416a-9d09-d49ebb03b1cb)

URLs like `https://github.com//` also load the new dashboard but that's a non-issue.

Thanks again, I'll definitely will keep using this!

**Comment by SamJakob** [comment]
Hey, thanks! 😄

Managed to come up with fixes for all of the issues you mentioned - the challenge was ensuring they all work whilst still making sure the feed only loads in the background for the homepage, but I think I have something fairly robust!

I'll push up the updates now (if you're on Chrome you'll be able to download and replace the old version, for Firefox I think you'll have to wait for it to be approved again).

**Comment by SamJakob** [comment]
Okay, new version submitted to Firefox (it's pending review, should be live in ~24 hours, or after the weekend), for Chrome you'll be able to pull/download the latest changes and install it as before. (Safari users - I'm working on a new release now - check the releases tab for v1.0.1.)
